services:
  app-entretien:
    build: ./auth.backend
    container_name: entretien_app
    image: entretien-api
    ports:
      - "8088:80"
    environment:
      - APP_ENV=production
      - DB_HOST=db-entretien
      - DB_PORT=3306
      - DB_DATABASE=entretien
      - DB_USERNAME=root
      - DB_PASSWORD=root
    networks:
      - entretien_network
    depends_on:
      - db-entretien
    restart: always

  db-entretien:
    image: mysql:8.0
    container_name: mysql_db_entretien
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=entretien
      - MYSQL_PASSWORD=entretien@123
    volumes:
      - mysql_data:/var/lib/mysql  
    networks:
      - entretien_network
    restart: always

  phpmyadmin-entretien:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_entretien
    environment:
      - PMA_HOST=db-entretien
      - PMA_PORT=3306
    ports:
      - "8089:80"
    networks:
      - entretien_network
    depends_on:
      - db-entretien
    restart: always

  frontend-entretien:
    build: ./auth.front
    container_name: frontend_entretien
    image: frontend-entretien
    ports:
      - "8090:80"
    environment:
      - NODE_ENV=production
    networks:
      - entretien_network
    restart: always

networks:
  entretien_network:
    driver: bridge

volumes:
  mysql_data:
